# Generated by Django 5.0.7 on 2024-07-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
                ('time_create', models.DateTimeField()),
                ('slag', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
