# Generated by Django 5.0.7 on 2024-08-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_newwork_alter_posts_content_alter_posts_slag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwork',
            name='file',
            field=models.ImageField(upload_to='uploads_models', verbose_name='изображение'),
        ),
    ]
