# Generated by Django 5.0.7 on 2024-08-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_newwork_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwork',
            name='file',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='uploads_models', verbose_name='изображение'),
        ),
    ]
