# Generated by Django 5.0.7 on 2024-08-17 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_alter_newwork_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='newwork',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
