# Generated by Django 5.0.7 on 2024-08-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_newwork_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newwork',
            name='text_content',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
