# Generated by Django 5.0.7 on 2024-08-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_newwork_text_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwork',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
