# Generated by Django 5.0.7 on 2024-08-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_newwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newwork',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
