# Generated by Django 5.0.7 on 2024-08-26 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_newwork_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newwork',
            options={'verbose_name': 'работы', 'verbose_name_plural': 'работы'},
        ),
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name': 'посты', 'verbose_name_plural': 'посты'},
        ),
        migrations.AddField(
            model_name='newwork',
            name='time_create_work',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата'),
        ),
    ]
